AppBundle\Entity\Product:
    product_cat1{1..30}:
        price: <randomFloat(2, 0.01, 999.99)>
        stock: <numberBetween(0, 100)>
        image: <imageUrl(890, 500, 'abstract', true, 'Faker')>
        subcategories: 2x @subcategory_cat1*

    product_cat2{1..30}:
        price: <randomFloat(2, 0.01, 999.99)>
        stock: <numberBetween(0, 100)>
        image: <imageUrl(890, 500, 'abstract', true, 'Faker')>
        subcategories: 2x @subcategory_cat2*

    product_cat3{1..30}:
        price: <randomFloat(2, 0.01, 999.99)>
        stock: <numberBetween(0, 100)>
        image: <imageUrl(890, 500, 'abstract', true, 'Faker')>
        subcategories: 2x @subcategory_cat3*