language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --dev --prefer-source

script: vendor/bin/phpunit

notifications:
  email:
    - vincent.composieux@gmail.com
    - andrieu.travail@gmail.com

matrix:
  allow_failures:
    - php: 7.0
