<?php

namespace AppBundle\Repository;

/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends \Doctrine\ORM\EntityRepository{


    //nom des acteurs tri ASC
    public function sql9(){

        $results = $this
            ->createQueryBuilder('acteur')
            ->select('acteur.nom, acteur.prenom')
            ->orderBy('acteur.nom')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

}
