<?php

namespace AppBundle\Repository;

/**
 * ContactSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
