<?php

namespace AppBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository{

    //tt les films
    public function sql1(){

        $results = $this
            ->createQueryBuilder('film')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //tt les realisateurs
    public function sql2(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('realisateurs.nom')
            ->join('film.realisateurs','realisateurs')
            ->groupBy('realisateurs.nom')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //titre et description des films
    public function sql3(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('film.titre AS t, film.description AS d')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //film à partir de 1980 et avec 'les' ds le titre
    public function sql4(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('film.titre')
            ->where('film.titre LIKE :titre')
            ->andWhere('YEAR(film.dateSortie) >= :date')
            ->setParameters([
                'titre' => '%les%',
                'date' => 1980
            ])
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //film d'akira kuroswa
    public function sql5(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('film.titre')
            ->join('film.realisateurs','realisateurs')
            ->where('realisateurs.nom = :nom')
            ->setParameters([
                'nom' => 'kurosawa'
            ])
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //film de sergio leone
    public function sql6(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('film.titre, GROUP_CONCAT(genres.nom)')
            ->join('film.realisateurs','realisateurs')
            ->join('film.genres','genres')
            ->where('realisateurs.nom = :nom')
            ->setParameters([
                'nom' => 'leone'
            ])
            ->groupBy('film.titre')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //nom des acteurs fr ds les films de spielberg
    public function sql7(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('acteurs.nom')
            ->join('film.realisateurs','realisateurs')
            ->join('film.acteurs','acteurs')
            ->join('acteurs.pays', 'pays')
            ->where('realisateurs.nom = :nom')
            ->andWhere('pays.nom = :pays')
            ->setParameters([
                'nom' => 'Spielberg',
                'pays' => 'france'
            ])
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //titre, date et nom real des films  1990 <  xxx  < 2000
    public function sql8(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('film.titre, film.dateSortie, realisateurs.nom')
            ->join('film.realisateurs','realisateurs')
            ->where('YEAR(film.dateSortie) BETWEEN :dateStart AND :dateEnd')
            ->setParameters([
                'dateStart' => 1990,
                'dateEnd' => '2000'
            ])
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //nombre de film par réalisateur
    public function sql10(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('realisateurs.nom, COUNT(film.id) AS compte')
            ->join('film.realisateurs','realisateurs')
            ->groupBy('realisateurs.id')
            ->orderBy('realisateurs.nom')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    //nombre de film sortis en 1968
    public function sql11(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('YEAR(film.dateSortie) AS sortie, COUNT(film.id) AS compte')
            ->where('YEAR(film.dateSortie) = :date')
            ->setParameters([
                'date' => 1968
            ])
            ->groupBy('sortie')
            ->getQuery()
            ->getSingleResult()
        ;

        return $results;
    }

    //film le plus recent
    public function sql12(){

        $results = $this
            ->createQueryBuilder('film')
            ->select('film.titre, film.dateSortie')
            ->orderBy('film.dateSortie', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult()
        ;

        return $results;
    }

    //film random
    public function sql13(){

        $results = $this
            ->createQueryBuilder('film')
            ->orderBy('RAND()')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult()
        ;

        return $results;
    }

}
