<?php

namespace AppBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository{

    public function getOneSubCategory($locale, $slug){

        $results = $this
            ->createQueryBuilder('sub_category')
            ->join('sub_category.translations','translations')

            ->where('translations.slug = :slug')
            ->andWhere('translations.locale = :locale')

            ->setParameters([
                'slug' => $slug,
                'locale' => $locale
            ])

            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $results;
    }

    public function getAllSubCategoriesByLocale($locale){

        $results = $this
            ->createQueryBuilder('sub_category')
            ->join('sub_category.translations','translations')
            ->where('translations.locale = :locale')

            ->setParameters([
                'locale' => $locale
            ])

            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    public function getAllSubCategoriesCategoryByLocale($locale){

        $results = $this
            ->createQueryBuilder('sub_category')
            ->select('category_translation.name, category.id')
            ->join('sub_category.translations','translations')

            ->join('sub_category.category','category')
            ->join('category.translations','category_translation')

            ->where('translations.locale = :locale')

            ->setParameters([
                'locale' => $locale
            ])

            ->groupBy('category.id')

            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

}
