<?php

namespace AppBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository{

    public function getOneSubCategory($locale, $slug){

        $results = $this
            ->createQueryBuilder('sub_category')
            ->join('sub_category.translations','translations')

            ->where('translations.slug = :slug')
            ->andWhere('translations.locale = :locale')

            ->setParameters([
                'slug' => $slug,
                'locale' => $locale
            ])

            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $results;
    }

}
