<?php

namespace AppBundle\Repository;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends \Doctrine\ORM\EntityRepository {

    public function findUserTokenByEmailToken($email, $token) {
        return $this->createQueryBuilder('userToken')
            ->select('userToken.expirationDate')
            ->where('userToken.email = :email')
            ->andWhere('userToken.token = :token')
            ->setParameters([
                'email' => $email,
                'token' => $token
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
